name: Build and Push Docker Image to Aliyun

on:
  push:
    branches:
      - rhwuHub-path-1  # 当 rhwuHub-path-1 分支有代码推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 在 Ubuntu 最新版本上运行此工作流程

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 检出代码，用于获取项目源代码

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
        # 设置 JDK 8 环境，用于构建 Maven 项目

      - name: Build with Maven
        run: mvn clean package
        # 使用 Maven 清理并打包项目

      - name: Log in to Aliyun Docker registry
        run: docker login --username=${{ secrets.ALIYUN_REGISTRY_USERNAME }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
        # 登录阿里云 Docker 镜像仓库，使用 GitHub secrets 中的用户名和密码

      - name: Build Docker image
        run: docker build -t registry.cn-hangzhou.aliyuncs.com/rhwu/hub:blog
        # 构建 Docker 镜像，标记为 latest 版本

      - name: Push Docker image
        run: docker push registry.cn-hangzhou.aliyuncs.com/rhwu/hub:blog
        # 推送 Docker 镜像到阿里云 Docker 仓库，latest 版本
